datasets: ['amazon-photo', 'pubmed', 'amazon-computers', 'coauthor-physics', 'flickr', 'com-amazon']
algs: ['gcn', 'ggnn', 'gat', 'gaan']

dir_out: paper_exp2_time_break/config_exp
dir_name: /mnt/data/wangzhaokang/wangyunpan/pyg-gnns/paper_exp2_time_break/dir_config_sqlite
dir_memory: /mnt/data/wangzhaokang/wangyunpan/pyg-gnns/paper_exp2_time_break/dir_config_json

infer_flag: false